### ISSUE TITLE
View full report on macOS

### ISSUE THREAD

**Issue by sjgoebel** [ANadig/YellowFruit#6]
Attempting to view full report generated the following error:

Error: EROFS: read-only file system, open '/private/var/folders/v2/c2vl4h6d049_0nwwlsvpyv580000gn/T/AppTranslocation/9AB38BA0-D84F-4165-B8A9-22F939471C17/d/YellowFruit.app/Contents/Resources/app/app/standings.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at Promise.all.then (file:///private/var/folders/v2/c2vl4h6d049_0nwwlsvpyv580000gn/T/AppTranslocation/9AB38BA0-D84F-4165-B8A9-22F939471C17/d/YellowFruit.app/Contents/Resources/app/app/js/render.js:70833:10)
    at <anonymous>

This occurred using a file created in 2.3.3 and opened in 2.4.2, but it also occurred in a test file created in 2.4.2.

I can view full report in 2.3.3 without error.

**Comment by ANadig** [comment]
Where are you running the application from? I can reproduce this on my machine by running it from the Downloads folder, but I can get around it by moving the application to (e.g.) the desktop.

**Comment by sjgoebel** [comment]
It was still in my downloads folder. I just moved it to the desktop, and it now works.

**Comment by ANadig** [comment]
Great. I will see if I can provide a more helpful error message when this happens.

**Comment by ANadig** [comment]
Addressed in v2.5.0
